-- Gamification fields on the canonical Prisma User table. Safe to rerun.
ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "xp" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "level" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "streak" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "best_streak" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "last_chore_date" TIMESTAMP(3);
