ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "notify_chores" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "notify_events" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "notify_messages" BOOLEAN NOT NULL DEFAULT true;
